[package]
name = "tradewinds-common"
version = "0.1.0"
edition = "2024"

[dependencies]
tradewinds-error = { path = "../tradewinds-error" }


serde = { version = "1.0", features = ["derive"] }
axum = { version = "0.8.4", features = ["macros"] }
tracing = "0.1"